a=int(input("Enter the number of Uinstrauctions to be tested:").strip())
for k in range(a):
    b=input("Enter the  uInstruction:").strip()
    c=b[4:]
    print("IU",c[2:5])
    print("SP1",c[5])
    print("Transmit",c[6])
    print("rnext",c[7:9])
    print("tnext",c[9:11])
    print("Rxallowed",c[11])
    print("wren",c[12])
    print("rden",c[13])
    print("Next Add",c[14])
    print("AC",c[15:20])
    print("Address",c[20:22])
    print("Rreg",c[22])
    print("rows",c[23])
    print("cols",c[24])
    print("next row",c[25])
    print("next col",c[26])
    print("data",c[27:29])
